// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProductInput struct {
	Name        string  `json:"name"`
	PriceCents  int     `json:"priceCents"`
	Description *string `json:"description,omitempty"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	PriceCents  int     `json:"priceCents"`
	Description *string `json:"description,omitempty"`
}
