package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"demo-graphql-subgraph/graph/model"
	"fmt"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	// TODO: In a real implementation, this would:
	// 1. Validate the input
	// 2. Call a service layer to create the product
	// 3. Persist to database
	// 4. Return the created product

	// Stub implementation for demo purposes
	product := &model.Product{
		ID:          "prod-new-123",
		Name:        input.Name,
		PriceCents:  input.PriceCents,
		Description: input.Description,
	}

	return product, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	// TODO: In a real implementation, this would fetch from a database or service

	// Stub implementation - returns a fake product
	// In production, return (nil, nil) if not found, not an error
	if id == "prod-404" {
		return nil, nil // Not found - not an error
	}

	product := &model.Product{
		ID:          id,
		Name:        "Example Product",
		PriceCents:  2999,
		Description: stringPtr("A sample product for demo purposes"),
	}

	return product, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, limit *int) ([]*model.Product, error) {
	// TODO: In a real implementation, this would:
	// 1. Fetch products from database with limit
	// 2. Use proper pagination
	// 3. Apply user permissions/filtering

	// Stub implementation - returns fake products
	products := []*model.Product{
		{
			ID:          "prod-1",
			Name:        "Widget Pro",
			PriceCents:  4999,
			Description: stringPtr("Professional grade widget"),
		},
		{
			ID:          "prod-2",
			Name:        "Gadget Ultra",
			PriceCents:  7999,
			Description: stringPtr("Ultra-premium gadget"),
		},
		{
			ID:          "prod-3",
			Name:        "Doohickey Standard",
			PriceCents:  1999,
			Description: nil,
		},
	}

	// Apply limit if specified
	if limit != nil && *limit < len(products) {
		products = products[:*limit]
	}

	return products, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// Helper function for pointer to string
func stringPtr(s string) *string {
	return &s
}

// TODO: Add new resolver methods below this comment
// When you add fields to existing types (like Product), gqlgen will generate
// new resolver methods that need implementation. Add them here.
// Example:
//
// func (r *productResolver) NewField(ctx context.Context, obj *model.Product) (string, error) {
//     // Implementation here
// }
